# Configurações para o Redis

# Configurações de recursos (pods, réplicas, etc.)
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Configurações de persistência
persistence:
  enabled: true
  size: 1Gi

# Configurações de segurança
auth:
  enabled: false
